version: "3.9"  # optional since v1.27.0
services:
  keycloak:
    image: jboss/keycloak
    environment: 
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/impexp/realm-export.json
    ports: 
      - 8080:8080 # Admin console (HTTP)
      - 8843:8443 # Admin console (HTTPS)
    volumes:
      - ./keycloak/impexp:/opt/jboss/keycloak/impexp